[workspace]
authors = ["Henry Cuzco <40706933+uiucmeche1317@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "marimo-demo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
marimo = ">=0.15.2,<0.16"
altair = ">=5.5.0,<6"
pandas = ">=2.3.2,<3"
seaborn = ">=0.13.2,<0.14"
duckdb = ">=1.3.2,<2"
sqlglot = ">=27.16.3,<28"
pyarrow = ">=21.0.0,<22"
